# Generated by Django 5.1.7 on 2026-03-03 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('visimages', 'VisImages dataset'), ('vis2023', 'IEEE VIS 2023'), ('vis2024', 'IEEE VIS 2024'), ('vis2025', 'IEEE VIS 2025'), ('seed_doi', 'Seed DOI list')], db_index=True, max_length=32)),
                ('doi', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('title', models.TextField()),
                ('authors', models.TextField(default='[]')),
                ('year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('track', models.CharField(choices=[('InfoVis', 'InfoVis'), ('VAST', 'VAST'), ('SciVis', 'SciVis'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=16)),
                ('abstract', models.TextField(blank=True, default='')),
                ('pdf_url', models.URLField(blank=True, default='', max_length=1024)),
                ('pdf_local_path', models.CharField(blank=True, default='', max_length=512)),
                ('keywords_extracted', models.TextField(default='[]')),
                ('topics_extracted', models.TextField(default='[]')),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'papers',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PaperFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure_index', models.IntegerField()),
                ('image_local_path', models.CharField(max_length=512)),
                ('is_visualization', models.BooleanField(blank=True, null=True)),
                ('vis_type', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('vis_type_confidence', models.FloatField(blank=True, null=True)),
                ('vis_type_raw', models.TextField(blank=True, default='')),
                ('annotation_source', models.CharField(blank=True, choices=[('visimages_json', 'VisImages annotation JSON'), ('llm_classified', 'LLM classified'), ('manual', 'Manually annotated')], default='', max_length=32)),
                ('gemini_file_id', models.CharField(blank=True, default='', max_length=512)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='academic.paper')),
            ],
            options={
                'db_table': 'paper_figures',
                'ordering': ['paper', 'figure_index'],
                'unique_together': {('paper', 'figure_index')},
            },
        ),
    ]
