# Generated by Django 5.1.7 on 2026-03-03 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepoSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('kaggle', 'Kaggle'), ('github', 'GitHub')], db_index=True, max_length=16)),
                ('source_id', models.CharField(max_length=256, unique=True)),
                ('url', models.URLField(max_length=1024)),
                ('title', models.TextField()),
                ('author', models.CharField(blank=True, default='', max_length=256)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='', max_length=32)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'repo_sources',
                'ordering': ['-stars', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='RepoArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('notebook', 'Jupyter Notebook'), ('script', 'Python Script'), ('markdown', 'Markdown')], default='notebook', max_length=16)),
                ('raw_content_path', models.CharField(blank=True, default='', max_length=512)),
                ('detected_libraries', models.TextField(default='[]')),
                ('detected_chart_types', models.TextField(default='[]')),
                ('detection_method', models.CharField(blank=True, choices=[('code_analysis', 'Code Analysis'), ('image_classification', 'Image Classification'), ('both', 'Both')], default='', max_length=32)),
                ('output_images_paths', models.TextField(default='[]')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='repository.reposource')),
            ],
            options={
                'db_table': 'repo_artifacts',
                'ordering': ['source', 'artifact_type'],
            },
        ),
    ]
