# Generated by Django 5.1.7 on 2026-03-03 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vis_type', models.CharField(db_index=True, max_length=64)),
                ('narrative_text', models.TextField()),
                ('source_traces', models.TextField(default='[]')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.CharField(blank=True, default='', max_length=128)),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narratives', to='academic.paperfigure')),
            ],
            options={
                'db_table': 'narratives',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_method', models.CharField(choices=[('chart_type_match', 'Chart Type Match'), ('keyword_match', 'Keyword Match')], default='chart_type_match', max_length=32)),
                ('match_confidence', models.FloatField(default=1.0)),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='repository.repoartifact')),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='academic.paperfigure')),
            ],
            options={
                'db_table': 'traces',
                'ordering': ['-match_confidence', 'created_at'],
                'unique_together': {('figure', 'artifact')},
            },
        ),
        migrations.CreateModel(
            name='DriftAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding_drift', models.CharField(choices=[('none', 'None'), ('minor', 'Minor'), ('major', 'Major')], default='none', max_length=8)),
                ('interaction_drift', models.CharField(choices=[('none', 'None'), ('minor', 'Minor'), ('major', 'Major')], default='none', max_length=8)),
                ('task_drift', models.CharField(choices=[('none', 'None'), ('minor', 'Minor'), ('major', 'Major')], default='none', max_length=8)),
                ('encoding_notes', models.TextField(blank=True, default='')),
                ('interaction_notes', models.TextField(blank=True, default='')),
                ('task_notes', models.TextField(blank=True, default='')),
                ('annotated_by', models.CharField(choices=[('llm', 'LLM'), ('manual', 'Manual')], default='llm', max_length=8)),
                ('annotated_at', models.DateTimeField(auto_now_add=True)),
                ('trace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drift_annotation', to='tracing.trace')),
            ],
            options={
                'db_table': 'drift_annotations',
                'ordering': ['-annotated_at'],
            },
        ),
    ]
